# -*- coding: utf-8 -*-
"""Lectura_Limpieza .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xO6BXdCuVz0JVeoDmOEMikgkx-d_kQ_a
"""

#Importan librerias
import numpy as np  
import matplotlib.pyplot as plt 
import pandas as pd

#Importamos la data de xls a csv
dfxls = pd.read_excel('StationsReport.xlsx')
dfxls.to_csv('StationsReport.csv', encoding='utf-8', index=False)
#Leemos la data
df = pd.read_csv('StationsReport.csv')

#Usaremos el nombre csv para trabajar el DataFrame
csvv = df

#Revisamos los registros
csvv.info()

csvv.shape

#Valores nulos dentro del data frame
print(csvv.isnull().sum())

#Separamos el dia de las fechas  
data1 = fecha1[  'DateTime'  ]. str  .split(pat =   '-'  , n =   1  , expand =   True  )  
data1 = data1.drop([  1  ], axis=  1  )  
fecha1[  'DateTime'  ] = data1
csvv

# Eliminamos comlumnas
csvv=csvv.drop(['PM10 µg/m3'], axis=1)
csvv=csvv.drop(['SO2 ppb'], axis=1)
csvv=csvv.drop(['CO2 ppm'], axis=1)
csvv=csvv.drop(['PM2.5 µg/m3'], axis=1)
csvv=csvv.drop(['Precipitacion mm'], axis=1)
csvv=csvv.drop(['Rad Solar W/M²'], axis=1)

csvv.columns= (['DateTime', 'CO_ppm', 'OZONO_ppb', 'NO_ppb', 'NO2_ppb', 'NOX_ppb','Vel_Viento_ms', 'Dir_Viento_Grados', 'Temperatura_C', 'HR'])

#Eliminamos valores nulos
csvv = csvv[csvv['CO_ppm'].notna()]
csvv = csvv[csvv['OZONO_ppb'].notna()]
csvv = csvv[csvv['NO_ppb'].notna()]
csvv = csvv[csvv['NO2_ppb'].notna()]
csvv = csvv[csvv['NOX_ppb'].notna()]
csvv = csvv[csvv['Vel_Viento_ms'].notna()]
csvv = csvv[csvv['Dir_Viento_Grados'].notna()]
csvv = csvv[csvv['Temperatura_C'].notna()]
csvv = csvv[csvv['HR'].notna()]